### ISSUE TITLE
Feedback/code review

### ISSUE THREAD

**Issue by ForNeVeR** [fourhundredfour/annoying-crlf#1]
Hello, you've asked for feedback in the [Russian F# Community chat](https://t.me/fsharp_chat) and I've decided it would be better to leave my feedback as an issue in this repository.

1. `File.ReadAllText` reads the whole file into memory. This will scale poorly for big files (consider someone wants to convert a big SQL dump using your program). You could maybe improve the memory impact by using `File.ReadLines` (and then concatenating them with `\n` and writing to an output stream), or maybe even reading the file asynchronously into a buffer/pipeline/channel and working on it chunk by chunk.
2. I can't see any point in defining `let replace (line: string) = line.Replace("\r\n", "\n")`, but probably it's just my issue.
3. You actually don't need `sw.Flush` and `sw.Close`. `use` block will take care of it automatically for a file stream.
4. Your syntax with `sw.Flush` and `sw.Close` is wrong anyway: currently you're acquiring the method references and ignoring these references, not calling them. Proper way to call them would be `sw.Flush(); sw.Close()` — note you don't need `ignore` since these methods return `void`/`unit`.
5. This snippet is incorrect (i.e. it doesn't do what you think it should):
   ```fsharp
   let writeInTempFile =
       use sw = new StreamWriter(Path.Join("/tmp/converted_files/", fileName))
       sw.Write (modifyText file)
       sw.Flush |> ignore
       sw.Close |> ignore
   writeInTempFile
   ```

   Here you've defined a **variable** (note it isn't a function) named `writeInTempFile` and its value was calculated eagerly. So, after you've finished with the `let` block, the file is already written, and the variable holds a value `()` (because it's what was returned by `ignore`). Mentioning of `writeInTempFile` at the next line just doesn't do anything.

   Probably you want to define a function here: `let writeInTempFile() = …`, and then call it: `writeInTempFile()`.
6. You've used `Array.map` in your `main` function in not-so-authentic way: it would be better to write `args |> Array.map (fun x -> …)`. I also think it would be better to split that expression into multiple lines (before each `|>` operator).
7. There's also a better function for pattern `smth |> Array.map … |> ignore`: use `Array.iter`.

**Comment by fourhundredfour** [comment]
Fixed in https://github.com/fourhundredfour/annoying-crlf/pull/2
